language: objective-c

matrix:
  include:
    - osx_image: xcode8

install:
 - gem install cocoapods
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
 - scripts/install_swiftlint.sh

script:
# - PROJECT_DIR=. scripts/swiftlint-code.sh
 - rake tests
# - PROJECT_DIR=. scripts/swiftlint-templates.sh
# - PROJECT_DIR=. scripts/check_templates.sh
 - pod lib lint SwiftGen.podspec
 - pod lib lint GenumKit/GenumKit.podspec
