name: Test Xcode

on:
  push:
    branches: stable
  pull_request:

jobs:
  test:
    name: Test Xcode
    runs-on: macos-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        name: Run tests
        run: bundle exec rake xcode:test
